name: Build and Push Docker Images

on:
  push:
    branches: [main]

env:
  DOCKERHUB_REPO_NEO4J_PROXY: ricklin/neo4j_proxy

jobs:
  echo_context:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"

  build-and-push-neo4j-proxy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Show Docker Hub username
        run: echo "DOCKER_USER is ${{ secrets.DOCKERHUB_USERNAME }}"

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Get short commit SHA
        id: vars
        run: echo "sha_short=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Build and push Neo4j Exporter image
        uses: docker/build-push-action@v5
        with:
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          push: true
          tags: |
            ${{ env.DOCKERHUB_REPO_NEO4J_PROXY }}:latest
            ${{ env.DOCKERHUB_REPO_NEO4J_PROXY }}:${{ steps.vars.outputs.sha_short }}
